volumes:
 postgres_volume:

services:
  pg-local:
    image: postgres:15.14-alpine3.22
    env_file:
      - "local.env"
    ports:
      - "54321:5432"
    volumes:
      - postgres_volume_local:/var/lib/postgresql/data    
